### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by frankvp11** [itsprakhar/Simple-DinoV2-Classification#2]
Hello!
I greatly appreciate this repo as it appears to be quite helpful.
However, I was wondering if you could give more information on the dataset that you used in training this custom segmentor. More specifically, how would I have to have the dataset setup? I know that some object detection models are quite annoying with this (yolov8, etc) and was wondering if this was the case aswell with segmentation. I would greatly appreciate it if you could forward me a copy of your labelled dataset (or the place where you got it from) or perhaps a tool that would allow me to properly annotate the pictures myself.
Thanks ,
Frank

**Comment by uttam-scai** [comment]
@frankvp11 @itsprakhar have you found the labelled dataset format?

**Comment by zhangjiayin20** [comment]
Hi! I believe that the dataset that author used is from https://www.kaggle.com/datasets/alxmamaev/flowers-recognition. It's a famous 5-class classification dataset. However, I have no idea where to get the segmentation labels. @frankvp11 @uttam-scai

**Comment by itsprakhar** [comment]
Hello @frankvp11, [This ](https://www.robots.ox.ac.uk/~vgg/data/bicos/) is the dataset I have used. If you have any specific dataset that you want to use this model with, please provide a link and I will add a dataloader for that.

**Comment by frankvp11** [comment]
Don't worry too much about it. I was just curious on how the training worked that's all. Thanks a lot though
